#!/usr/bin/python

import web.httpserver
from netbars.traffic import application

port = 3001
# this is a server with no logging
s = web.httpserver.WSGIServer(("0.0.0.0", port), application)
print "serving http on port %s" % port
s.start()


