#!/usr/bin/python

""" read netbars /traffic resource every 2 seconds and send it to
graphite/carbon database for plotting """

import restkit # need restkit 2.x
import simplejson, traceback
import sys, os
from influxdb import InfluxDBClient

from twisted.internet import reactor, task

netbarsServer = "http://localhost:3001/"
updateSecs = 2

influx = InfluxDBClient('localhost', 9060, 'root', 'root', 'main')
src = restkit.Resource(netbarsServer + "traffic")

def _update():
    inBytes, outBytes = simplejson.loads(src.get().body_string())
    influx.write_points([
        dict(measurement='bytesPerSec', tags={'source': 'isp', 'dest': 'bang'}, fields={'value': inBytes}),
        dict(measurement='bytesPerSec', tags={'source': 'bang', 'dest': 'isp'}, fields={'value': outBytes}),
        
    ], time_precision='s')

def update():
    try:
        _update()
    except Exception:
        traceback.print_exc()
        os.abort()

task.LoopingCall(update).start(updateSecs)
reactor.run()
